export const correctToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWQiOiI5NzBmMDIzMi02YzA2LTExZWQtYTFlYi0wMjQyYWMxMjAwMDIiLCJpYXQiOjE1MTYyMzkwMjJ9.8RISrSnMjaxxDA-EGmBDMQWmxxVvCXvxMmEYn1fl4Mg";

export const emptyPayloadToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyfQ.GotXZnyA_3esVFiTbXUrqM5KHgcMBRlDvFKB6Mi3sPA"

export const wrongSecretKeyToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyfQ.oWcqvFmq7rZ8Af0c8s2esd-YSmwYrLIZo8MBgcIrHSA"